accent = "#bdae93"
cursor = "#bdae93"
foreground = "#d4be98"
background = "#442e22"
selection_foreground = "#ebdbb2"
selection_background = "#442E22"

color0 = "#3c3836"
color1 = "#ea6962"
color2 = "#d4be98"
color3 = "#d8a657"
color4 = "#d4be98"
color5 = "#d3869b"
color6 = "#d4be98"
color7 = "#d4be98"
color8 = "#3c3836"
color9 = "#ea6962"
color10 = "#d4be98"
color11 = "#d8a657"
color12 = "#d4be98"
color13 = "#d3869b"
color14 = "#d4be98"
color15 = "#d4be98"
