accent = "#CACCCA"
cursor = "#DDDDDD"
foreground = "#DDDDDD"
background = "#1a1a1a"
selection_foreground = "#DDDDDD"
selection_background = "#353436"

color0 = "#131313"
color1 = "#3A3A3A"
color2 = "#3A3A3A"
color3 = "#57564F"
color4 = "#8F8F8F"
color5 = "#CACCCA"
color6 = "#9E9E9E"
color7 = "#DDDDDD"
color8 = "#272727"
color9 = "#323232"
color10 = "#373636"
color11 = "#474646"
color12 = "#4C4D4D"
color13 = "#1E1D1E"
color14 = "#1E1D1E"
color15 = "#131313"
